import Head from 'next/head'
import Image from 'next/image'
import React from 'react';
import styles from '../styles/Home.module.scss'
import {SubTitle, Title, TitleContainer} from './components/titles';
import {Accordion, Toggle} from './components/accordion';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.title}>
                    <TitleContainer>
                        <Title>Shortcodes</Title>
                        <SubTitle>Useful and Indispensable.</SubTitle>
                    </TitleContainer>
                </div>
                <div className={styles.accordion}>
                    <Accordion
                        title={'Accordion'}
                        items={[
                            {title: 'title 1', content: 'text item 1',},
                            {title: 'title 2', content: 'text item 2',},
                            {
                                title: 'title 3',
                                content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur, expedita!',
                            },
                            {
                                title: 'title 4',
                                content: 'Top_level_declarations_in_d_ts_files_must_start_with_either_a_declare_or_export_modifier_1046'
                            },
                        ]}
                    />
                </div>
                <div className={styles.toggle}>
                    <Toggle
                        title={'Toggle'}
                        items={[
                            {title: 'title 1', content: 'text item 1',},
                            {title: 'title 2', content: 'text item 2',},
                            {
                                title: 'title 3',
                                content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur, expedita!',
                            },
                            {
                                title: 'title 4',
                                content: 'Top_level_declarations_in_d_ts_files_must_start_with_either_a_declare_or_export_modifier_1046'
                            },
                        ]}
                    />
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
                </a>
            </footer>
        </div>
    )
}
