<?php
/**
 * The header.
 *
 * This is the template that displays all of the <head> section and everything up until main.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage Twenty_Twenty_One
 * @since Twenty Twenty-One 1.0
 */
$pathToFiles = get_theme_file_uri() . '/nextjs/out';
?>
<!doctype html>
<html <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo('charset'); ?>" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <!-- nextJS -->
  <meta charSet="utf-8" />
  <title>Create Next App</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="<?=$pathToFiles?>/favicon.ico" />
  <meta name="next-head-count" content="5" />
  <link rel="preload" href="<?=$pathToFiles?>/_next/static/css/969e9fed165d262fea95.css" as="style" />
  <link rel="stylesheet" href="<?=$pathToFiles?>/_next/static/css/969e9fed165d262fea95.css" data-n-g="" />
  <link rel="preload" href="<?=$pathToFiles?>/_next/static/css/6b1d636be5aaf1bb051f.css" as="style" />
  <link rel="stylesheet" href="<?=$pathToFiles?>/_next/static/css/6b1d636be5aaf1bb051f.css" data-n-p="" />
  <noscript data-n-css=""></noscript>
  <script defer="" nomodule="" src="<?=$pathToFiles?>/_next/static/chunks/polyfills-a54b4f32bdc1ef890ddd.js"></script>
  <script src="<?=$pathToFiles?>/_next/static/chunks/webpack-9fc9ab40a062a7008df3.js" defer=""></script>
  <script src="<?=$pathToFiles?>/_next/static/chunks/framework-92300432a1172ef1338b.js" defer=""></script>
  <script src="<?=$pathToFiles?>/_next/static/chunks/main-0786f78015b8368a3815.js" defer=""></script>
  <script src="<?=$pathToFiles?>/_next/static/chunks/pages/_app-39b5b78494f24d57ad73.js" defer=""></script>
  <script src="<?=$pathToFiles?>/_next/static/chunks/29107295-2648cb5e919f7c78c7cc.js" defer=""></script>
  <script src="<?=$pathToFiles?>/_next/static/chunks/pages/index-45dafe7eac86acd99603.js" defer=""></script>
  <script src="<?=$pathToFiles?>/_next/static/aFXKsPQziUqf99okHceI9/_buildManifest.js" defer=""></script>
  <script src="<?=$pathToFiles?>/_next/static/aFXKsPQziUqf99okHceI9/_ssgManifest.js" defer=""></script>
  <!-- /nextJS -->

  <?php wp_head(); ?>
</head>

<body>
<div id="__next">
